export const STORAGE_KEYS = {
  USER_SESSION: 'USER_SESSION',
  PARTNER_PROFILE: 'PARTNER_PROFILE',
  KYC_STATUS: 'KYC_STATUS',
  BUSINESS_PROFILE: 'BUSINESS_PROFILE',
  MANDATORY_FLOW: 'MANDATORY_FLOW',
  BRANCHES: 'BRANCHES',
  EMPLOYEES: 'EMPLOYEES',
  SERVICES: 'SERVICES',
  BOOKINGS: 'BOOKINGS',
  WALLET: 'WALLET',
} as const;
